version: "3"

services:
  app:
    build: ./
    volumes:
      - ./:/src/2019techc/
    working_dir: /src/2019techc/
    ports:
      - 9000:9000
  web:
    build: ./nginx/
    ports:
      - 80:80
    volumes:
      - ./public/static/:/public/static/
